package com.bclaus.rsps.server.vd.content.achievements;

/**
 * 
 * @author Jason http://www.rune-server.org/members/jason
 * @date Mar 27, 2014
 */
public enum AchievementType {

	KILL_ROCK_CRAB, KILL_NPC, ROPES, KILL_ABYSSAL_DEMON, SITE, VOTE, PROTECTION, PEST_CONTROL, HELP, CLAN, SLAYER, SOCIAL_SLAYER, FRIENDS, FORUM, PVP, KILL_BLACK_DRAGON, KILL_NECHRYAEL, HUNTER, DONATE, SHARK_FISHER, ZAMORAK_BREWER, TRACKER, KILL_DARK_BEAST, KILL_VENENATIS, KILL_VETION, KILL_SCORPIA, KILL_CALLISTO, BARROWS_CHEST_COUNT, KILL_JUNGLE_DEMON, DEFENDER, CLUE_SCROLL, MEDIUM_CLUE, HARD_CLUE, ELITE_CLUE
}
